name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/crupter
            asset_name: crupter-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/crupter.exe
            asset_name: crupter-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/crupter
            asset_name: crupter-macos-intel

    steps:
    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release --locked

    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}

    - name: Add Apple Silicon target
      if: matrix.os == 'macOS-latest'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin

    - name: Build for Apple Silicon
      if: matrix.os == 'macOS-latest'
      run: cargo build --release --locked --target aarch64-apple-darwin

    - name: Upload Apple Silicon binary
      uses: actions/upload-artifact@v2
      if: matrix.os == 'macOS-latest'
      with:
        name: crupter-macos-arm
        path: target/aarch64-apple-darwin/release/crupter