name: Crupter Build on Push
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  testBuildStatus:
    name: Test Build Status
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features --verbose
    - name: Add Apple Silicon target
      if: matrix.os == 'macOS-latest'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - uses: actions-rs/cargo@v1
      if: matrix.os == 'macOS-latest'
      with:
        command: build
        args: --release --all-features --verbose --target aarch64-apple-darwin

