name: Crupter Build on Push
# This workflow is triggered on pushes to the repository.
on: [push]
runs-on: 
strategy:
  matrix:
    os: [windows-latest, macOS-latest, ubuntu-18.04]

jobs:
  testBuildStatus:
    name: Test Build Status
    runs-on: ${{ matrix.os }}
  steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1  
    - name: Build
      run: cargo build --release

