name: Crupter Build on Push
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  testBuildStatus:
    name: Test Build Status
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-18.04]
    steps:
    - name: Checkout
      uses: actions/checkout@1
      with:
        fetch-depth: 1  
    - name: Build
      run: cargo build --release --verbose

